name: Run Docker

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 7 * * *'
  push:
    branches: [ alpine ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ alpine ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    runs-on: ubuntu-22.04
    steps:

      - uses: actions/checkout@main

      - name: Login to Docker Hub
        uses: docker/login-action@main
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@main
        with:
          images: tigefa/ffmpeg

      - name: Build and push Docker images
        uses: docker/build-push-action@main
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GH_PAT }}

